### ISSUE TITLE
Create database and tables

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#1]
Create the base database and tables needed for all the functionality

**Comment by mwauramuchiri** [comment]
A new database?

**Comment by mwauramuchiri** [comment]
What about the tests tables?
Lemme do everything about tests, I've woken up with psych yake.
Okay?

**Comment by AllanJeremy** [comment]
Yes , a new database. Let me create the tables for everything, then I can export the structure over to you.

**Comment by mwauramuchiri** [comment]
okay sure

**Comment by AllanJeremy** [comment]
Eh, need name for the database

**Comment by mwauramuchiri** [comment]
esomo

**Comment by AllanJeremy** [comment]
that's the other database's name
and don't say esomo-2

**Comment by AllanJeremy** [comment]
Done creating here it is. the structure of all the tables, if I missed anything, feel free to add + let me know

https://drive.google.com/open?id=0B0kPYrW8iZenZzdDS3ZRTjJHb0E

**Comment by mwauramuchiri** [comment]
I've added the recovery table, same structure as the old one
just incase...

**Comment by AllanJeremy** [comment]
alright, reupload & send?

**Comment by mwauramuchiri** [comment]
You deleted the other database?
You can just export the table then import

**Comment by AllanJeremy** [comment]
I still have it, actually I can duplicate the table structure only, will do that, thanks.
