### ISSUE TITLE
Login redirect issue

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#12]
When logging in as any account that is not a teacher account, we are still redirected to #classroom , this should redirect to the primary active tab for each type of account.

Found this out a few moments before the demo, so I ended up holding to a presentation instead.

**Comment by mwauramuchiri** [comment]
Will improve the function

**Comment by mwauramuchiri** [comment]
Fixed.
Feel like the code is too long for such an important part of the site.
I will improve it later.

**Comment by mwauramuchiri** [comment]
enhanced.

**Comment by AllanJeremy** [comment]
> enhanced.

Alright, great
