### ISSUE TITLE
Convert all javascript modal templates into php code

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#18]
Adding and removing the modals dynamically in the DOM causes the page to load unnecessarily. If we have the modals in the DOM then simply display them with appropriate data when need be, the loading times for creating and removing the elements from the DOM can be avoided.

> In this case we are trading of a few milliseconds of initial load time for better performance in the page in stead of the previous javascript template method where we would have slightly faster load time for the page but this would be at the expense of the performance of the page during product usage

Below is a checklist to crosscheck what sections are done

- [x] Superuser section
- [x] Principal section
- [x] Teacher section
- [x] Student section

**Comment by AllanJeremy** [comment]
Tested working php based navigation. If any issue arises on your end, feel free to reopen the issue (@mwauramuchiri)

PS. Commented out all the navigation logic in dashboard.js as it is not needed

**Comment by mwauramuchiri** [comment]
This issue is about the modals though, not navigation

**Comment by mwauramuchiri** [comment]
Correction btw. Manipulating the DOM and its elements is a load for the hardware, manipulating takes milliseconds if hardware is capable.

**Comment by AllanJeremy** [comment]
> This issue is about the modals though, not navigation

Holy... I didn't even notice that. Well... Reopen it?

> Manipulating the DOM and its elements is a load for the hardware, manipulating takes milliseconds if hardware is capable.

For the modals, since they are already working, we can just retain how they function. As long as they don't break.
