### ISSUE TITLE
#! links prevent navigation from opening respective tabs

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#19]

**Comment by mwauramuchiri** [comment]
Test the site now then close

**Comment by AllanJeremy** [comment]
> Test the site now then close

on it

> Edit: @mwauramuchiri  Tested this in the teacher section. Navigation works right
> Will test the other sections as we go on, but so far so good.
> Good fix.

**Comment by AllanJeremy** [comment]
Edit: Tested this in the teacher section. Navigation works right

Good fix.

**Comment by AllanJeremy** [comment]
@mwauramuchiri This again :(

> Navigation does not work for `teacher section` and `student section`. 
> Navigation still works for `superuser section` and `principal section`

**Comment by mwauramuchiri** [comment]
Mine works fine

**Comment by AllanJeremy** [comment]
Hmm, pull and let me know if it still works?
