### ISSUE TITLE
Create Login and Superuser UI

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#2]
Create the login for students/staff as well as the superuser frontend based on the [illustrations provided](https://drive.google.com/file/d/0B0kPYrW8iZenc1VUM2pyd2pFWUk/view?usp=sharing).

 Feel free to adjust the colors as you see fit as well as interface changes that work to our advantage

**Comment by mwauramuchiri** [comment]
Almost done.
Question, do you think there's need for a search bar on the header for the superuser?
Also, about the 'create, import, manage' tabs, are they tabs or links to scroll to the right 'section'? I'm not sure which is better.

**Comment by mwauramuchiri** [comment]
I think tabs are better. 
1. Faster to create
2. Scrolling will be a little bit messy on phone due to distance of divs from the top of the screen + offseting it according to the header's height... **...in short, it demands more javascript for a good scrolling navigation style through the divs**

I'm going with tabs.

**Comment by mwauramuchiri** [comment]
Done now.
Lemme upload/commit

Tell me if you find any issue or what I should change

**Comment by AllanJeremy** [comment]
Sorry was offline when you commented. Done with the login functionality for all account types, students and staff.  

> I think tabs are better. 
> 1. Faster to create
> 2. Scrolling will be a little bit messy on phone due to distance of divs from the top of the screen + offseting it according to the header's height... ...in short, it demands more javascript for a good scrolling navigation style through the divs
> 
> I'm going with tabs.

that's perfectly fine, whatever works better is the better option in this case

and no there's no need for the search bar as far as I know.  

> Tell me if you find any issue or what I should change
> There was minor issues such as color of text in the dropdown.
> A more major issue is that prefilled content sort of overlaps labels

added `Materialize.updateTextFields()` in document ready on both index.php and login.php but not sure how effective that is.

On the logging in, a request. Instead of the page reloading when a user enters the incorrect information; it should tell them that the information they entered is incorrect. (AJAX). Once this is done, the login section is completely done. Haven't tested students yet, but I'm pretty certain it works.

I have created the error boxes above the input fields for the forms with unique ids
`id = "invalid_student_login"` for **students login form** and `id = "invalid_admin_login"` for the **staff login form** with default classes of `hide` so that you can easily add/remove that class from them

Other than that, really slick design, love the colors and transitions and general feel of everything. Nailed the dark theme for the login by the way. Haven't spent enough time in the superuser section but that looked pretty damn good as well, and true to the designs or even better. 

Hopefully you rested today, because I did a lot of additions that may mess up stuff you have done if you added anything. Check commits

**Comment by mwauramuchiri** [comment]
alafu,
I don't have the table student_accounts...

**Comment by AllanJeremy** [comment]
Oh, let me re-export for you

You can just import it as the new table, already copied the recovery table from the other database

Here's [the updated database ](https://drive.google.com/file/d/0B0kPYrW8iZenZzdDS3ZRTjJHb0E/view?usp=sharing) with the updated table structures.

**Comment by mwauramuchiri** [comment]
Thanks, but how do I login?
I don't have any credentials* in the db.

**Comment by AllanJeremy** [comment]
I think you already figured that out. Also, removing the password fields, accounts will be created with default passwords same as the username

Going to be easier to tell if password has been changed that way
