### ISSUE TITLE
Resource Upload bug

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#28]
When uploading resources, we don't get a message showing whether or not the upload was successful, even though it does actually upload

**Comment by mwauramuchiri** [comment]
Fixed this.
You can test it out and close if it's fixed

**Comment by AllanJeremy** [comment]
Tested, the progress is being displayed. Closing this specific issue

We need to do the resource viewer page though. Will open that as a different issue
