### ISSUE TITLE
Staff login account type dropdown does not show

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#4]
The account type dropdown for checking what kind of account you want to login as a staff member does not show. It is still seen in the markup when you view source, but not visible in the site. Probably  a js issue since it worked before [this commit](https://github.com/AllanJeremy/esomo-upgrade/commit/e87671d867e09c6fe79a1b3a0aa8162572b5a990)

Here's a screenshot showing what's going on
![screenshot_10](https://cloud.githubusercontent.com/assets/5031274/20619863/bf8dc4c8-b307-11e6-87b5-08ed7e7594ca.png)

**Comment by mwauramuchiri** [comment]
It is still like that?
Lemme pull your changes then I see if mine too gets to do that

**Comment by AllanJeremy** [comment]
yes,finally, you're back, been waiting forever. Deadline coming up

**Comment by mwauramuchiri** [comment]
Fixed this
