### ISSUE TITLE
Cannot edit classrooms

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#6]
Somehow cannot edit classrooms. When I click the edit button for classrooms, nothing happens. I may  have broken it, but I don't remember touching the classroom code. Please fix as soon as possible before working on anything else @mwauramuchiri

**Comment by mwauramuchiri** [comment]
Still has this bug?

**Comment by mwauramuchiri** [comment]
Oh the error is
**Warning: Illegal string offset 'stream_id' in C:\wamp64\www\Gits\esomo-2\handlers\db_info.php on line 1104**

illegal string offset 'stream_id', 'student_ids', 'class_name', 'subject_id' and 'classes'

**Comment by mwauramuchiri** [comment]
Tell me when you fix it

**Comment by AllanJeremy** [comment]
> Still has this bug?

yes.
