### ISSUE TITLE
Edit classroom student display bug

### ISSUE THREAD

**Issue by AllanJeremy** [AllanJeremy/esomo-upgrade#8]
When a classroom is being edited, student name duplicates occur. 

Essentially, students in the classroom cannot be added to the classroom again or should be checked by default in the modal window for editing. In this case, it would be much easier to simply update the students in a classroom(remove or add) by checking or unchecking the names in the modal dialogue that appears

**Comment by mwauramuchiri** [comment]
The duplication error is in the php.
Ajax get receives duplicate datas.

**Comment by AllanJeremy** [comment]
> The duplication error is in the php.
> Ajax get receives duplicate datas.

Which function is being used to get the data

**Comment by mwauramuchiri** [comment]
db_info.php function is **GetAllStudentsNotInClass**

**Comment by AllanJeremy** [comment]
Alright, let me check it . You can edit code here like so `GetAllStudentsNotInClass`
